# Chaining this file to the main docker-compose file adds
# a default processing node instance. This is best for users
# who are just getting started with WebODM.

version: '2.1'
services:
  webapp:
    depends_on:
      - node-odm-1
    environment:
      - WO_CREATE_DEFAULT_PNODE=YES
  node-odm-1:
    image: opendronemap/nodeodm
    container_name: node-odm-1
    ports:
      - "3000"
    restart: on-failure:10
    oom_score_adj: 500
